<div class="modal fade" id="data-book" tabindex="-1" role="dialog" aria-labelledby="data-bookLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-title">Add Book</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="book_form">
                    <div class="mb-3 form-label-group">
                        <input type="text" name="nome" id="nome" class="form-control">
                        <label for="nome">Nome</label>
                    </div>
                    <div class="mb-3 form-label-group">
                        <input type="text" name="escritor" id="escritor" class="form-control">
                        <label for="escritor">Escritor</label>
                    </div>
                    <div class="mb-3 form-label-group">
                        <input type="text" name="editora" id="editora" class="form-control">
                        <label for="editora">Editora</label>
                    </div>
                    <div class="mb-3 form-label-group">
                        <input type="text" name="genero" id="genero" class="form-control">
                        <label for="genero">Gênero</label>
                    </div>
                    <div class="mb-3 form-label-group">
                        <input type="text" name="paginas" id="paginas" class="form-control">
                        <label for="paginas">Páginas</label>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-primary" id="add_button" name="add_button" value="Add">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal-backdrop fade show" id="modal_backdrop" style="display:none"></div>